### ISSUE TITLE
Confirm with backend/frontend if Information architecture is inline with what is being created and filter IA if needed.

### ISSUE THREAD

**Issue by Quemmies3** [zuri-training/Proj_qr_gen_team_58#10]

**Comment by OlubummoKolawole** [comment]
I constantly made sure what was being created was inline with the Information Architecture and made edits when I had to, just to keep it up to date with what the Frontend/backend could work with

**Comment by Ladestr4** [comment]
Developed IA for Unauthorized User based on research objectives and user stories.

**Comment by OlubummoKolawole** [comment]
https://www.figma.com/file/hTDLt78DVD4KiIDLy1LgsY/Untitled?node-id=16%3A2
