### ISSUE TITLE
Design the landing page and develop content for it 

### ISSUE THREAD

**Issue by Quemmies3** [zuri-training/Proj_qr_gen_team_58#11]
Ensure it is made responsive so it can be viewed on mobile easily.

**Comment by Nlemorisacharles** [comment]
Task Completed ✅

**Comment by Sope-Kingsley** [comment]
Task completed

**Comment by Marvelpeakson** [comment]
I participated in designing the landing page. 

Created the Faq Division and prototyped it

Rearranged the why QReate section, About QReate and the steps below with illustrations. 

Designed the QR Code types Division

Design the contact us division

**Comment by Nlemorisacharles** [comment]
@Marvelpeakson  haba nauu 😂😂💔

**Comment by mairiam** [comment]
Task completed
