### ISSUE TITLE
Design login, register pages and the success page. 

### ISSUE THREAD

**Issue by Quemmies3** [zuri-training/Proj_qr_gen_team_58#14]

**Comment by Vctr-echo** [comment]
We've completed the pages, however, isn't this GitHub task for frontend guys? I guess it's a misunderstanding. Educate me, if otherwise.

**Comment by Vctr-echo** [comment]
@destinyarupi Ok, I'm clarified now. Thanks.

**Comment by AfeezahW** [comment]
Completed days ago.
