### ISSUE TITLE
Design Landing page for Desktop and mobile. 

### ISSUE THREAD

**Issue by Marvelpeakson** [zuri-training/Proj_qr_gen_team_58#49]
I participated in designing the landing page. 

Created the Faq Division and prototyped it

Rearranged the why QReate section, About QReate and the steps below with illustrations. 

Designed the QR Code types Division

Design the contact us division

**Comment by Nlemorisacharles** [comment]
@Marvelpeakson ahhhhh 😦

**Comment by Nlemorisacharles** [comment]
Headed the UI design team.
Task Completed ✅

**Comment by mairiam** [comment]
Worked with the head of the UI team, Charles and completed this task
